

misc_dict = {
'Development Status :: 1 - Planning': None,
'Development Status :: 2 - Pre-Alpha': None,
'Development Status :: 3 - Alpha': None,
'Development Status :: 4 - Beta': None,
'Development Status :: 5 - Production/Stable': None,
'Development Status :: 6 - Mature': None,
'Development Status :: 7 - Inactive': None,
}

env_dict = {
'Environment :: Console': None,
'Environment :: Console :: Curses': None,
'Environment :: Console :: Framebuffer': None,
'Environment :: Console :: Newt': None,
'Environment :: Console :: svgalib': None,
'Environment :: Handhelds/PDAs': None,
'Environment :: MacOS X': None,
'Environment :: MacOS X :: Aqua': None,
'Environment :: MacOS X :: Carbon': None,
'Environment :: MacOS X :: Cocoa': None,
'Environment :: No Input/Output (Daemon)': None,
'Environment :: Other Environment': None,
'Environment :: Plugins': None,
'Environment :: Web Environment': None,
'Environment :: Web Environment :: Buffet': None,
'Environment :: Web Environment :: Mozilla': None,
'Environment :: Web Environment :: ToscaWidgets': None,
'Environment :: Win32 (MS Windows)': None,
'Environment :: X11 Applications': None,
'Environment :: X11 Applications :: Gnome': None,
'Environment :: X11 Applications :: GTK': None,
'Environment :: X11 Applications :: KDE': None,
'Environment :: X11 Applications :: Qt': None,
'Framework :: Buildout': None,
'Framework :: Chandler': None,
'Framework :: CubicWeb': None,
'Framework :: Django': None,
'Framework :: IDLE': None,
'Framework :: Paste': None,
'Framework :: Plone': None,
'Framework :: Pylons': None,
'Framework :: Setuptools Plugin': None,
'Framework :: Trac': None,
'Framework :: TurboGears': None,
'Framework :: TurboGears :: Applications': None,
'Framework :: TurboGears :: Widgets': None,
'Framework :: Twisted': None,
'Framework :: ZODB': None,
'Framework :: Zope2': None,
'Framework :: Zope3': None,
}

audience_dict = {
'Intended Audience :: Customer Service': None,
'Intended Audience :: Developers': None,
'Intended Audience :: Education': None,
'Intended Audience :: End Users/Desktop': None,
'Intended Audience :: Financial and Insurance Industry': None,
'Intended Audience :: Healthcare Industry': None,
'Intended Audience :: Information Technology': None,
'Intended Audience :: Legal Industry': None,
'Intended Audience :: Manufacturing': None,
'Intended Audience :: Other Audience': None,
'Intended Audience :: Religion': None,
'Intended Audience :: Science/Research': None,
'Intended Audience :: System Administrators': None,
'Intended Audience :: Telecommunications Industry': None,
}

license_dict = {
'License :: Aladdin Free Public License (AFPL)': 'Aladdin',
'License :: DFSG approved': None,
'License :: Eiffel Forum License (EFL)': None,
'License :: Free For Educational Use': None,
'License :: Free For Home Use': None,
'License :: Free for non-commercial use': 'free-noncomm',
'License :: Freely Distributable': 'freedist',
'License :: Free To Use But Restricted': None,
'License :: Freeware': None,
'License :: Netscape Public License (NPL)': None,
'License :: Nokia Open Source License (NOKOS)': None,
'License :: OSI Approved': None,
'License :: OSI Approved :: Academic Free License (AFL)': 'AFL-2.1',
'License :: OSI Approved :: Apache Software License': 'Apache-2.0',
'License :: OSI Approved :: Apple Public Source License': 'Apple',
'License :: OSI Approved :: Artistic License': 'Artistic-2',
'License :: OSI Approved :: Attribution Assurance License': None,
'License :: OSI Approved :: BSD License': 'BSD-2',
'License :: OSI Approved :: Common Public License': 'CPL-1.0',
'License :: OSI Approved :: Eiffel Forum License': None,
'License :: OSI Approved :: GNU Affero General Public License v3': None,
'License :: OSI Approved :: GNU Free Documentation License (FDL)': 'FDL-1.2',
'License :: OSI Approved :: GNU General Public License (GPL)': 'GPL-2',
'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)': 'LGPL-2.1',
'License :: OSI Approved :: IBM Public License': 'IBM',
'License :: OSI Approved :: Intel Open Source License': 'Intel',
'License :: OSI Approved :: Jabber Open Source License': None,
'License :: OSI Approved :: MIT License': 'MIT',
'License :: OSI Approved :: MITRE Collaborative Virtual Workspace License (CVW)': None,
'License :: OSI Approved :: Motosoto License': None,
'License :: OSI Approved :: Mozilla Public License 1.0 (MPL)': 'MPL-1.0',
'License :: OSI Approved :: Mozilla Public License 1.1 (MPL 1.1)': 'MPL-1.1',
'License :: OSI Approved :: Nethack General Public License': 'nethack',
'License :: OSI Approved :: Nokia Open Source License': 'nokia',
'License :: OSI Approved :: Open Group Test Suite License': None,
'License :: OSI Approved :: Python License (CNRI Python License)': 'PYTHON',
'License :: OSI Approved :: Python Software Foundation License': 'PSF-2.4',
'License :: OSI Approved :: Qt Public License (QPL)': 'QPL-1.0',
'License :: OSI Approved :: Ricoh Source Code Public License': None,
'License :: OSI Approved :: Sleepycat License': 'DB',
'License :: OSI Approved :: Sun Industry Standards Source License (SISSL)': None,
'License :: OSI Approved :: Sun Public License': None,
'License :: OSI Approved :: University of Illinois/NCSA Open Source License': 'ncsa-1.3',
'License :: OSI Approved :: Vovida Software License 1.0': None,
'License :: OSI Approved :: W3C License': 'W3C',
'License :: OSI Approved :: X.Net License': None,
'License :: OSI Approved :: zlib/libpng License': 'ZLIB',
'License :: OSI Approved :: Zope Public License': None,
'License :: Other/Proprietary License': None,
'License :: Public Domain': 'public-domain',
}

lang_dict = {
'Natural Language :: Afrikaans': None,
'Natural Language :: Arabic': None,
'Natural Language :: Bengali': None,
'Natural Language :: Bosnian': None,
'Natural Language :: Bulgarian': None,
'Natural Language :: Catalan': None,
'Natural Language :: Chinese (Simplified)': None,
'Natural Language :: Chinese (Traditional)': None,
'Natural Language :: Croatian': None,
'Natural Language :: Czech': None,
'Natural Language :: Danish': None,
'Natural Language :: Dutch': None,
'Natural Language :: English': None,
'Natural Language :: Esperanto': None,
'Natural Language :: Finnish': None,
'Natural Language :: French': None,
'Natural Language :: German': None,
'Natural Language :: Greek': None,
'Natural Language :: Hebrew': None,
'Natural Language :: Hindi': None,
'Natural Language :: Hungarian': None,
'Natural Language :: Icelandic': None,
'Natural Language :: Indonesian': None,
'Natural Language :: Italian': None,
'Natural Language :: Japanese': None,
'Natural Language :: Javanese': None,
'Natural Language :: Korean': None,
'Natural Language :: Latin': None,
'Natural Language :: Latvian': None,
'Natural Language :: Macedonian': None,
'Natural Language :: Malay': None,
'Natural Language :: Marathi': None,
'Natural Language :: Norwegian': None,
'Natural Language :: Panjabi': None,
'Natural Language :: Persian': None,
'Natural Language :: Polish': None,
'Natural Language :: Portuguese': None,
'Natural Language :: Portuguese (Brazilian)': None,
'Natural Language :: Romanian': None,
'Natural Language :: Russian': None,
'Natural Language :: Serbian': None,
'Natural Language :: Slovak': None,
'Natural Language :: Slovenian': None,
'Natural Language :: Spanish': None,
'Natural Language :: Swedish': None,
'Natural Language :: Tamil': None,
'Natural Language :: Telugu': None,
'Natural Language :: Thai': None,
'Natural Language :: Turkish': None,
'Natural Language :: Ukranian': None,
'Natural Language :: Urdu': None,
'Natural Language :: Vietnamese': None,
}

os_dict = {
'Operating System :: BeOS': None,
'Operating System :: MacOS': None,
'Operating System :: MacOS :: MacOS 9': None,
'Operating System :: MacOS :: MacOS X': None,
'Operating System :: Microsoft': None,
'Operating System :: Microsoft :: MS-DOS': None,
'Operating System :: Microsoft :: Windows': None,
'Operating System :: Microsoft :: Windows :: Windows 3.1 or Earlier': None,
'Operating System :: Microsoft :: Windows :: Windows 95/98/2000': None,
'Operating System :: Microsoft :: Windows :: Windows CE': None,
'Operating System :: Microsoft :: Windows :: Windows NT/2000': None,
'Operating System :: OS/2': None,
'Operating System :: OS Independent': None,
'Operating System :: Other OS': None,
'Operating System :: PalmOS': None,
'Operating System :: PDA Systems': None,
'Operating System :: POSIX': None,
'Operating System :: POSIX :: AIX': None,
'Operating System :: POSIX :: BSD': None,
'Operating System :: POSIX :: BSD :: BSD/OS': None,
'Operating System :: POSIX :: BSD :: FreeBSD': None,
'Operating System :: POSIX :: BSD :: NetBSD': None,
'Operating System :: POSIX :: BSD :: OpenBSD': None,
'Operating System :: POSIX :: GNU Hurd': None,
'Operating System :: POSIX :: HP-UX': None,
'Operating System :: POSIX :: IRIX': None,
'Operating System :: POSIX :: Linux': None,
'Operating System :: POSIX :: Other': None,
'Operating System :: POSIX :: SCO': None,
'Operating System :: POSIX :: SunOS/Solaris': None,
'Operating System :: Unix': None,
}

prog_lang = {
'Programming Language :: Ada': None,
'Programming Language :: APL': None,
'Programming Language :: ASP': None,
'Programming Language :: Assembly': None,
'Programming Language :: Awk': None,
'Programming Language :: Basic': None,
'Programming Language :: C': None,
'Programming Language :: C#': None,
'Programming Language :: C++': None,
'Programming Language :: Cold Fusion': None,
'Programming Language :: Cython': None,
'Programming Language :: Delphi/Kylix': None,
'Programming Language :: Dylan': None,
'Programming Language :: Eiffel': None,
'Programming Language :: Emacs-Lisp': None,
'Programming Language :: Erlang': None,
'Programming Language :: Euler': None,
'Programming Language :: Euphoria': None,
'Programming Language :: Forth': None,
'Programming Language :: Fortran': None,
'Programming Language :: Haskell': None,
'Programming Language :: Java': None,
'Programming Language :: JavaScript': None,
'Programming Language :: Lisp': None,
'Programming Language :: Logo': None,
'Programming Language :: ML': None,
'Programming Language :: Modula': None,
'Programming Language :: Objective C': None,
'Programming Language :: Object Pascal': None,
'Programming Language :: OCaml': None,
'Programming Language :: Other': None,
'Programming Language :: Other Scripting Engines': None,
'Programming Language :: Pascal': None,
'Programming Language :: Perl': None,
'Programming Language :: PHP': None,
'Programming Language :: Pike': None,
'Programming Language :: Pliant': None,
'Programming Language :: PL/SQL': None,
'Programming Language :: PROGRESS': None,
'Programming Language :: Prolog': None,
'Programming Language :: Python': None,
'Programming Language :: Python :: 2': None,
'Programming Language :: Python :: 2.3': None,
'Programming Language :: Python :: 2.4': None,
'Programming Language :: Python :: 2.5': None,
'Programming Language :: Python :: 2.6': None,
'Programming Language :: Python :: 2.7': None,
'Programming Language :: Python :: 3': None,
'Programming Language :: Python :: 3.0': None,
'Programming Language :: Python :: 3.1': None,
'Programming Language :: Python :: 3.2': None,
'Programming Language :: REBOL': None,
'Programming Language :: Rexx': None,
'Programming Language :: Ruby': None,
'Programming Language :: Scheme': None,
'Programming Language :: Simula': None,
'Programming Language :: Smalltalk': None,
'Programming Language :: SQL': None,
'Programming Language :: Tcl': None,
'Programming Language :: Unix Shell': None,
'Programming Language :: Visual Basic': None,
'Programming Language :: XBasic': None,
'Programming Language :: YACC': None,
'Programming Language :: Zope': None,
}

topic_dict = {
'Topic :: Adaptive Technologies': 'app-misc',
'Topic :: Artistic Software': 'media-gfx',
'Topic :: Communications': 'net-misc',
'Topic :: Communications :: BBS': 'net-misc',
'Topic :: Communications :: Chat': 'net-misc',
'Topic :: Communications :: Chat :: AOL Instant Messenger': 'net-im',
'Topic :: Communications :: Chat :: ICQ': 'net-misc',
'Topic :: Communications :: Chat :: Internet Relay Chat': 'net-irc',
'Topic :: Communications :: Chat :: Unix Talk': 'net-misc',
'Topic :: Communications :: Conferencing': 'app-office',
'Topic :: Communications :: Email': 'mail-client',
'Topic :: Communications :: Email :: Address Book': 'mail-client',
'Topic :: Communications :: Email :: Email Clients (MUA)': 'net-client',
'Topic :: Communications :: Email :: Filters': 'net-filter',
'Topic :: Communications :: Email :: Mailing List Servers': 'net-mail',
'Topic :: Communications :: Email :: Mail Transport Agents': 'net-mta',
'Topic :: Communications :: Email :: Post-Office': 'net-mail',
'Topic :: Communications :: Email :: Post-Office :: IMAP': 'net-mail',
'Topic :: Communications :: Email :: Post-Office :: POP3': 'net-mail',
'Topic :: Communications :: Fax': 'net-misc',
'Topic :: Communications :: FIDO': 'net-misc',
'Topic :: Communications :: File Sharing': 'net-p2p',
'Topic :: Communications :: File Sharing :: Gnutella': 'net-p2p',
'Topic :: Communications :: File Sharing :: Napster': 'net-p2p',
'Topic :: Communications :: Ham Radio': 'media-radio',
'Topic :: Communications :: Internet Phone': 'net-voip',
'Topic :: Communications :: Telephony': 'app-mobilephone',
'Topic :: Communications :: Usenet News': 'net-nntp',
'Topic :: Database': 'dev-db',
'Topic :: Database :: Database Engines/Servers': 'dev-db',
'Topic :: Database :: Front-Ends': 'dev-db',
'Topic :: Desktop Environment': 'x11-wm',
'Topic :: Desktop Environment :: File Managers': 'x11-wm',
'Topic :: Desktop Environment :: Gnome': 'x11-wm',
'Topic :: Desktop Environment :: GNUstep': 'x11-wm',
'Topic :: Desktop Environment :: K Desktop Environment (KDE)': 'x11-wm',
'Topic :: Desktop Environment :: K Desktop Environment (KDE) :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: PicoGUI': 'x11-wm',
'Topic :: Desktop Environment :: PicoGUI :: Applications': 'x11-wm',
'Topic :: Desktop Environment :: PicoGUI :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Screen Savers': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Afterstep': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Afterstep :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: Applets': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Blackbox': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Blackbox :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: CTWM': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: CTWM :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: Enlightenment': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Enlightenment :: Epplets': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Enlightenment :: Themes DR15': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: Enlightenment :: Themes DR16': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: Enlightenment :: Themes DR17': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: Fluxbox': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Fluxbox :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: FVWM': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: FVWM :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: IceWM': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: IceWM :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: MetaCity': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: MetaCity :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: Oroborus': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Oroborus :: Themes': 'x11-theme',
'Topic :: Desktop Environment :: Window Managers :: Sawfish': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Sawfish :: Themes 0.30': 'x11-themes',
'Topic :: Desktop Environment :: Window Managers :: Sawfish :: Themes pre-0.30': 'x11-themes',
'Topic :: Desktop Environment :: Window Managers :: Waimea': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Waimea :: Themes': 'x11-themes',
'Topic :: Desktop Environment :: Window Managers :: Window Maker': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Window Maker :: Applets': 'x11-wm',
'Topic :: Desktop Environment :: Window Managers :: Window Maker :: Themes': 'x11-themes',
'Topic :: Desktop Environment :: Window Managers :: XFCE': 'xfce-base',
'Topic :: Desktop Environment :: Window Managers :: XFCE :: Themes': 'xfce-extra',
'Topic :: Documentation': 'app-doc',
'Topic :: Education': 'app-misc',
'Topic :: Education :: Computer Aided Instruction (CAI)': 'app-misc',
'Topic :: Education :: Testing': 'app-misc',
'Topic :: Games/Entertainment': 'games-misc',
'Topic :: Games/Entertainment :: Arcade': 'games-arcade',
'Topic :: Games/Entertainment :: Board Games': 'games-board',
'Topic :: Games/Entertainment :: First Person Shooters': 'games-fps',
'Topic :: Games/Entertainment :: Fortune Cookies': 'games-misc',
'Topic :: Games/Entertainment :: Multi-User Dungeons (MUD)': 'games-mud',
'Topic :: Games/Entertainment :: Puzzle Games': 'games-puzzle',
'Topic :: Games/Entertainment :: Real Time Strategy': 'games-strategy',
'Topic :: Games/Entertainment :: Role-Playing': 'games-rpg',
'Topic :: Games/Entertainment :: Side-Scrolling/Arcade Games': 'games-arcade',
'Topic :: Games/Entertainment :: Simulation': 'games-simulation',
'Topic :: Games/Entertainment :: Turn Based Strategy': 'games-strategy',
'Topic :: Home Automation': 'app-misc',
'Topic :: Internet': 'net-misc',
'Topic :: Internet :: File Transfer Protocol (FTP)': 'net-ftp',
'Topic :: Internet :: Finger': 'net-misc',
'Topic :: Internet :: Log Analysis': 'net-misc',
'Topic :: Internet :: Name Service (DNS)': 'net-nds',
'Topic :: Internet :: Proxy Servers': 'net-proxy',
'Topic :: Internet :: WAP': 'net-www',
'Topic :: Internet :: WWW/HTTP': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Browsers': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Dynamic Content': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: CGI Tools/Libraries': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Message Boards': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: News/Diary': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Page Counters': 'net-www',
'Topic :: Internet :: WWW/HTTP :: HTTP Servers': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Indexing/Search': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Site Management': 'net-www',
'Topic :: Internet :: WWW/HTTP :: Site Management :: Link Checking': 'net-www',
'Topic :: Internet :: WWW/HTTP :: WSGI': 'net-www',
'Topic :: Internet :: WWW/HTTP :: WSGI :: Application': 'net-www',
'Topic :: Internet :: WWW/HTTP :: WSGI :: Middleware': 'net-www',
'Topic :: Internet :: WWW/HTTP :: WSGI :: Server': 'net-www',
'Topic :: Internet :: Z39.50': 'net-misc',
'Topic :: Multimedia': 'media-gfx',
'Topic :: Multimedia :: Graphics': 'media-gfx',
'Topic :: Multimedia :: Graphics :: 3D Modeling': 'media-gfx',
'Topic :: Multimedia :: Graphics :: 3D Rendering': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Capture': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Capture :: Digital Camera': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Capture :: Scanners': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Capture :: Screen Capture': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Editors': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Editors :: Raster-Based': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Editors :: Vector-Based': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Graphics Conversion': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Presentation': 'media-gfx',
'Topic :: Multimedia :: Graphics :: Viewers': 'media-gfx',
'Topic :: Multimedia :: Sound/Audio': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Analysis': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Capture/Recording': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: CD Audio': 'app-cdr',
'Topic :: Multimedia :: Sound/Audio :: CD Audio :: CD Playing': 'app-cdr',
'Topic :: Multimedia :: Sound/Audio :: CD Audio :: CD Ripping': 'app-cdr',
'Topic :: Multimedia :: Sound/Audio :: CD Audio :: CD Writing': 'app-cdr',
'Topic :: Multimedia :: Sound/Audio :: Conversion': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Editors': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: MIDI': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Mixers': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Players': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Players :: MP3': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Sound Synthesis': 'media-sound',
'Topic :: Multimedia :: Sound/Audio :: Speech': 'media-sound',
'Topic :: Multimedia :: Video': 'media-video',
'Topic :: Multimedia :: Video :: Capture': 'media-video',
'Topic :: Multimedia :: Video :: Conversion': 'media-video',
'Topic :: Multimedia :: Video :: Display': 'media-libs',
'Topic :: Multimedia :: Video :: Non-Linear Editor': 'media-video',
'Topic :: Office/Business': 'app-office',
'Topic :: Office/Business :: Financial': 'app-office',
'Topic :: Office/Business :: Financial :: Accounting': 'app-office',
'Topic :: Office/Business :: Financial :: Investment': 'app-office',
'Topic :: Office/Business :: Financial :: Point-Of-Sale': 'app-office',
'Topic :: Office/Business :: Financial :: Spreadsheet': 'app-office',
'Topic :: Office/Business :: Groupware': 'app-office',
'Topic :: Office/Business :: News/Diary': 'app-office',
'Topic :: Office/Business :: Office Suites': 'app-office',
'Topic :: Office/Business :: Scheduling': 'app-office',
'Topic :: Other/Nonlisted Topic': 'app-misc',
'Topic :: Printing': 'net-print',
'Topic :: Religion': 'app-misc',
'Topic :: Scientific/Engineering': 'sci-misc',
'Topic :: Scientific/Engineering :: Artificial Intelligence': 'sci-mathematics',
'Topic :: Scientific/Engineering :: Astronomy': 'sci-astronomy',
'Topic :: Scientific/Engineering :: Atmospheric Science': 'sci-geosciences',
'Topic :: Scientific/Engineering :: Bio-Informatics': 'sci-biology',
'Topic :: Scientific/Engineering :: Chemistry': 'sci-chemistry',
'Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)': 'sci-misc',
'Topic :: Scientific/Engineering :: GIS': 'sci-geosciences',
'Topic :: Scientific/Engineering :: Human Machine Interfaces': 'sci-misc',
'Topic :: Scientific/Engineering :: Image Recognition': 'sci-misc',
'Topic :: Scientific/Engineering :: Information Analysis': 'sci-mathematics',
'Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator': 'sci-misc',
'Topic :: Scientific/Engineering :: Mathematics': 'sci-mathematics',
'Topic :: Scientific/Engineering :: Medical Science Apps.': 'sci-biology',
'Topic :: Scientific/Engineering :: Physics': 'sci-physics',
'Topic :: Scientific/Engineering :: Visualization': 'sci-visualization',
'Topic :: Security': 'app-crypt',
'Topic :: Security :: Cryptography': 'app-crypt',
'Topic :: Sociology': 'app-misc',
'Topic :: Sociology :: Genealogy': 'app-misc',
'Topic :: Sociology :: History': 'app-misc',
'Topic :: Software Development': 'dev-util',
'Topic :: Software Development :: Assemblers': 'dev-lang',
'Topic :: Software Development :: Bug Tracking': 'dev-util',
'Topic :: Software Development :: Build Tools': 'dev-util',
'Topic :: Software Development :: Code Generators': 'dev-lang',
'Topic :: Software Development :: Compilers': 'dev-lang',
'Topic :: Software Development :: Debuggers': 'dev-util',
'Topic :: Software Development :: Disassemblers': 'dev-util',
'Topic :: Software Development :: Documentation': 'app-doc',
'Topic :: Software Development :: Embedded Systems': 'dev-embedded',
'Topic :: Software Development :: Internationalization': 'app-i18n',
'Topic :: Software Development :: Interpreters': 'app-i18n',
'Topic :: Software Development :: Libraries': 'dev-libs',
'Topic :: Software Development :: Libraries :: Application Frameworks': 'dev-libs',
'Topic :: Software Development :: Libraries :: Java Libraries': 'dev-java',
'Topic :: Software Development :: Libraries :: Perl Modules': 'dev-perl',
'Topic :: Software Development :: Libraries :: PHP Classes': 'dev-php',
'Topic :: Software Development :: Libraries :: Pike Modules': 'dev-util',
'Topic :: Software Development :: Libraries :: pygame': 'dev-python',
'Topic :: Software Development :: Libraries :: Python Modules': 'dev-python',
'Topic :: Software Development :: Libraries :: Ruby Modules': 'dev-ruby',
'Topic :: Software Development :: Libraries :: Tcl Extensions': 'dev-tcltk',
'Topic :: Software Development :: Localization': 'app-i18n',
'Topic :: Software Development :: Object Brokering': 'net-misc',
'Topic :: Software Development :: Object Brokering :: CORBA': 'net-misc',
'Topic :: Software Development :: Pre-processors': 'dev-util',
'Topic :: Software Development :: Quality Assurance': 'dev-util',
'Topic :: Software Development :: Testing': 'dev-util',
'Topic :: Software Development :: Testing :: Traffic Generation': 'dev-util',
'Topic :: Software Development :: User Interfaces': 'dev-python',
'Topic :: Software Development :: Version Control': 'dev-util',
'Topic :: Software Development :: Version Control :: CVS': 'dev-util',
'Topic :: Software Development :: Version Control :: RCS': 'dev-util',
'Topic :: Software Development :: Version Control :: SCCS': 'dev-util',
'Topic :: Software Development :: Widget Sets': 'dev-python',
'Topic :: System': 'sys-apps',
'Topic :: System :: Archiving': 'app-arch',
'Topic :: System :: Archiving :: Backup': 'app-arch',
'Topic :: System :: Archiving :: Compression': 'app-arch',
'Topic :: System :: Archiving :: Mirroring': 'app-arch',
'Topic :: System :: Archiving :: Packaging': 'app-arch',
'Topic :: System :: Benchmark': 'app-benchmarks',
'Topic :: System :: Boot': 'sys-boot',
'Topic :: System :: Boot :: Init': 'sys-boot',
'Topic :: System :: Clustering': 'sys-cluster',
'Topic :: System :: Console Fonts': 'media-fonts',
'Topic :: System :: Distributed Computing': 'sys-cluster',
'Topic :: System :: Emulators': 'app-emulation',
'Topic :: System :: Filesystems': 'sys-fs',
'Topic :: System :: Hardware': 'sys-kernel',
'Topic :: System :: Hardware :: Hardware Drivers': 'sys-kernel',
'Topic :: System :: Hardware :: Mainframes': 'sys-cluster',
'Topic :: System :: Hardware :: Symmetric Multi-processing': 'sys-cluster',
'Topic :: System :: Installation/Setup': 'app-admin',
'Topic :: System :: Logging': 'app-admin',
'Topic :: System :: Monitoring': 'app-admin',
'Topic :: System :: Networking': 'net-misc',
'Topic :: System :: Networking :: Firewalls': 'net-firewall',
'Topic :: System :: Networking :: Monitoring': 'net-misc',
'Topic :: System :: Networking :: Monitoring :: Hardware Watchdog': 'net-misc',
'Topic :: System :: Networking :: Time Synchronization': 'net-misc',
'Topic :: System :: Operating System': 'sys-kernel',
'Topic :: System :: Operating System Kernels': 'sys-kernel',
'Topic :: System :: Operating System Kernels :: BSD': 'sys-kernel',
'Topic :: System :: Operating System Kernels :: GNU Hurd': 'sys-kernel',
'Topic :: System :: Operating System Kernels :: Linux': 'sys-kernel',
'Topic :: System :: Power (UPS)': 'sys-power',
'Topic :: System :: Recovery Tools': 'app-backup',
'Topic :: System :: Shells': 'app-shells',
'Topic :: System :: Software Distribution': 'app-admin',
'Topic :: System :: Systems Administration': 'app-admin',
'Topic :: System :: Systems Administration :: Authentication/Directory': 'net-nds',
'Topic :: System :: Systems Administration :: Authentication/Directory :: LDAP': 'net-nds',
'Topic :: System :: Systems Administration :: Authentication/Directory :: NIS': 'net-nds',
'Topic :: System :: System Shells': 'app-shells',
'Topic :: Terminals': 'x11-terms',
'Topic :: Terminals :: Serial': 'net-misc',
'Topic :: Terminals :: Telnet': 'net-misc',
'Topic :: Terminals :: Terminal Emulators/X Terminals': 'x11-terms',
'Topic :: Text Editors': 'app-editors',
'Topic :: Text Editors :: Documentation': 'app-doc',
'Topic :: Text Editors :: Emacs': 'app-emacs',
'Topic :: Text Editors :: Integrated Development Environments (IDE)': 'dev-util',
'Topic :: Text Editors :: Text Processing': 'app-text',
'Topic :: Text Editors :: Word Processors': 'app-office',
'Topic :: Text Processing': 'app-text',
'Topic :: Text Processing :: Filters': 'app-text',
'Topic :: Text Processing :: Fonts': 'app-text',
'Topic :: Text Processing :: General': 'app-text',
'Topic :: Text Processing :: Indexing': 'app-text',
'Topic :: Text Processing :: Linguistic': 'app-text',
'Topic :: Text Processing :: Markup': 'app-text',
'Topic :: Text Processing :: Markup :: HTML': 'app-text',
'Topic :: Text Processing :: Markup :: LaTeX': 'app-text',
'Topic :: Text Processing :: Markup :: SGML': 'app-text',
'Topic :: Text Processing :: Markup :: VRML': 'app-text',
'Topic :: Text Processing :: Markup :: XML': 'app-text',
'Topic :: Utilities': 'app-text',
}
